version: '3'
services:
  vote:
    image: localhost:5000/vote
    ports:
      - "5001:80"
  results:
    image: localhost:5000/result
    ports:
      - "5002:80"
  send-data:
    image: localhost:5000/send-data
  worker:
    image: localhost:5000/worker