version: "3"
services:
  worker:
    build:
      context: ./worker
    networks:
      - registry-network
  vote:
    build:
      context: ./seed-data
    networks:
      - registry-network
  send-data:
    build :
      context: ./seed-data
    networks:
      - registry-network
  result:
    build:
      context: ./result
    networks:
      - registry-network

networks:
  registry-network:
    external: true