version: "3"
services:
  udagram-reverseproxy:
    image: localhost:5000/reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
    networks:
      - udagram

  backend-user:
    image: localhost:5000/udagram-api-user
    environment:
      POSTGRES_USERNAME: udagram
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: udagramdb
      POSTGRES_HOST: postgres
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udagram-bucket-1234567
      JWT_SECRET: testing
      URL: "http://localhost:5000"


  backend-feed:
    image: localhost:5000/udagram-api-feed
    environment:
      POSTGRES_USERNAME: udagram
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: udagramdb
      POSTGRES_HOST: postgres
      AWS_REGION: us-east-1
      AWS_PROFILE: default
      AWS_BUCKET: udagram-bucket-1234567
      JWT_SECRET: testing
      URL: "http://localhost:5000"

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: udagram
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: udagramdb

networks:
  udagram:

